import type { InfluencerProfile } from './types';

/** Local influencer pool for rule-based matching (name, category, audience, traits, platforms). */
export const INFLUENCER_DATASET: InfluencerProfile[] = [
  {
    id: 'inf-01',
    name: 'Maya Chen',
    shortDescription: 'Beauty creator known for SPF-first routines, honest wear tests, and derm-credible breakdowns.',
    categories: ['Beauty', 'Lifestyle'],
    audienceTags: ['Gen Z women', 'skincare-first', 'US', 'product researchers'],
    traits: ['GRWM', 'product testing', 'ingredient education', 'before/after'],
    platforms: ['TikTok', 'Instagram'],
  },
  {
    id: 'inf-02',
    name: 'Jordan Ellis',
    shortDescription: 'Streetwear storyteller blending runway context with thrift and stadium tunnel fits.',
    categories: ['Fashion', 'Lifestyle', 'Sports'],
    audienceTags: ['Millennials', 'menswear', 'sneaker culture', 'US'],
    traits: ['styling', 'event coverage', 'UGC lookbooks', 'brand collaborations'],
    platforms: ['Instagram', 'YouTube'],
  },
  {
    id: 'inf-03',
    name: 'Priya Nair',
    shortDescription: 'Wellness voice focused on recovery rituals, sleep, and science-literate supplement reviews.',
    categories: ['Wellness', 'Lifestyle'],
    audienceTags: ['affluent millennials', 'global', 'evidence-minded'],
    traits: ['long-form reviews', 'expert interviews', 'routine building', 'product testing'],
    platforms: ['YouTube', 'Instagram', 'Newsletter'],
  },
  {
    id: 'inf-04',
    name: 'Theo Marquez',
    shortDescription: 'Chef-creator translating pantry staples into restaurant-level plates and beverage pairings.',
    categories: ['Food & Beverage', 'Lifestyle'],
    audienceTags: ['home cooks', 'LATAM', 'family households'],
    traits: ['recipe series', 'sponsored integrations', 'retail tie-ins', 'live cooking'],
    platforms: ['TikTok', 'Instagram', 'YouTube'],
  },
  {
    id: 'inf-05',
    name: 'Riley Park',
    shortDescription: 'Music and culture host with strong red-carpet commentary and artist interview access.',
    categories: ['Music', 'Entertainment', 'Lifestyle'],
    audienceTags: ['Gen Z', 'pop culture', 'North America'],
    traits: ['interviews', 'event coverage', 'reactive social', 'brand integrations'],
    platforms: ['Instagram', 'YouTube', 'X'],
  },
  {
    id: 'inf-06',
    name: 'Amara Okonkwo',
    shortDescription: 'Luxury fashion editor-turned-creator; sharp on tailoring, accessories, and editorial pacing.',
    categories: ['Fashion', 'Entertainment'],
    audienceTags: ['affluent', 'Europe', 'editorial readers'],
    traits: ['lookbooks', 'behind-the-scenes', 'designer commentary', 'press-friendly'],
    platforms: ['Instagram', 'YouTube'],
  },
  {
    id: 'inf-07',
    name: 'Chris Dalton',
    shortDescription: 'Athlete-creator focused on training transparency, recovery tech, and locker-room storytelling.',
    categories: ['Sports', 'Wellness'],
    audienceTags: ['sports fans', 'Gen Z men', 'US'],
    traits: ['documentary style', 'product testing', 'sponsor integrations', 'training vlogs'],
    platforms: ['Instagram', 'TikTok', 'YouTube'],
  },
  {
    id: 'inf-08',
    name: 'Sienna Brooks',
    shortDescription: 'Clean-girl beauty aesthetic with emphasis on minimal routines and accessible glam.',
    categories: ['Beauty', 'Lifestyle'],
    audienceTags: ['Gen Z women', 'UK', 'makeup-light'],
    traits: ['GRWM', 'get-ready shorts', 'brand tutorials', 'creator seeding'],
    platforms: ['TikTok', 'Instagram'],
  },
  {
    id: 'inf-09',
    name: 'Devon Lee',
    shortDescription: 'Tech and lifestyle reviewer who stress-tests wearables and travel gear on real trips.',
    categories: ['Lifestyle', 'Wellness'],
    audienceTags: ['tech-curious', 'millennials', 'global'],
    traits: ['stress tests', 'comparison reviews', 'long-form explainers', 'travel hooks'],
    platforms: ['YouTube', 'Instagram'],
  },
  {
    id: 'inf-10',
    name: 'Nina Kovács',
    shortDescription: 'Budapest-based creator bridging runway week, vintage sourcing, and sustainable fashion.',
    categories: ['Fashion', 'Lifestyle'],
    audienceTags: ['Europe', 'sustainability-minded', 'fashion students'],
    traits: ['vintage styling', 'event diaries', 'educational content', 'collaborations'],
    platforms: ['Instagram', 'TikTok'],
  },
  {
    id: 'inf-11',
    name: 'Marcus Webb',
    shortDescription: 'Comedy-leaning entertainer with high share velocity and music festival field reporting.',
    categories: ['Entertainment', 'Music'],
    audienceTags: ['Gen Z', 'humor-first', 'US'],
    traits: ['reactive memes', 'festival coverage', 'brand sketches', 'creator challenges'],
    platforms: ['TikTok', 'Instagram', 'YouTube'],
  },
  {
    id: 'inf-12',
    name: 'Elena Vasquez',
    shortDescription: 'Latina lifestyle creator focused on family occasions, hosting, and premium grocery storytelling.',
    categories: ['Food & Beverage', 'Lifestyle'],
    audienceTags: ['Latinx', 'family', 'US'],
    traits: ['table styling', 'seasonal recipes', 'retail storytelling', 'sponsored series'],
    platforms: ['Instagram', 'TikTok', 'YouTube'],
  },
  {
    id: 'inf-13',
    name: 'Harper Singh',
    shortDescription: 'Skincare scientist-communicator translating clinical claims into plain language.',
    categories: ['Beauty', 'Wellness'],
    audienceTags: ['ingredient-conscious', 'millennials', 'global'],
    traits: ['ingredient education', 'lab visits', 'product testing', 'credibility building'],
    platforms: ['YouTube', 'Instagram'],
  },
  {
    id: 'inf-14',
    name: 'Owen Fitzgerald',
    shortDescription: 'Outdoor and endurance creator pairing gear tests with cinematic trail storytelling.',
    categories: ['Sports', 'Lifestyle'],
    audienceTags: ['outdoor enthusiasts', 'US', 'premium gear'],
    traits: ['field tests', 'sponsor integrations', 'cinematic edits', 'community challenges'],
    platforms: ['YouTube', 'Instagram'],
  },
  {
    id: 'inf-15',
    name: 'Zara Ahmed',
    shortDescription: 'Modest fashion and beauty creator with strong styling tutorials and occasion dressing.',
    categories: ['Fashion', 'Beauty', 'Lifestyle'],
    audienceTags: ['MENA', 'UK', 'faith-conscious fashion'],
    traits: ['tutorials', 'GRWM', 'occasion styling', 'brand partnerships'],
    platforms: ['Instagram', 'YouTube', 'TikTok'],
  },
  {
    id: 'inf-16',
    name: 'Felix Romero',
    shortDescription: 'Nightlife and beverage culture host with bartender credibility and premium cocktail builds.',
    categories: ['Food & Beverage', 'Entertainment'],
    audienceTags: ['urban millennials', 'LATAM', 'nightlife'],
    traits: ['bar takeovers', 'recipe builds', 'event coverage', 'sponsored tastings'],
    platforms: ['Instagram', 'TikTok', 'YouTube'],
  },
  {
    id: 'inf-17',
    name: 'Taylor Kim',
    shortDescription: 'K-beauty adjacent creator mixing texture-first demos with travel retail discovery.',
    categories: ['Beauty', 'Lifestyle'],
    audienceTags: ['Gen Z', 'Asia-Pacific', 'texture-focused'],
    traits: ['texture demos', 'travel retail', 'GRWM', 'product testing'],
    platforms: ['TikTok', 'Instagram', 'YouTube'],
  },
  {
    id: 'inf-18',
    name: 'Vivienne Hart',
    shortDescription: 'Prestige fragrance and editorial beauty voice with print-adjacent visual discipline.',
    categories: ['Beauty', 'Fashion', 'Lifestyle'],
    audienceTags: ['luxury buyers', 'North America', 'editorial'],
    traits: ['editorial shoots', 'fragrance storytelling', 'event coverage', 'limited drops'],
    platforms: ['Instagram', 'YouTube'],
  },
];
